### ISSUE TITLE
Gimbal Control always times out

### ISSUE THREAD

**Issue by MandingoMagnus** [aimas-lund/siyi-camera-controller#21]
Hello,

While testing the controller for the ZR30 camera, we had some problems with the "set_attitude_callback" method. When we send a command to the camera to set the gimbal position, the gimbal always overshoots the final position (both in negative and positive error) until the timeout time is reached, at which point it stops, but we never managed to set the desired position.

The only case where we are able to set the desired position is when all angles are zero (home position). I attach a video so you can see this behaviour.

Thank you very much for your assistance.

Best regards,

Guillem.

https://github.com/aimas-lund/siyi-camera-controller/assets/163417952/f8fc5f6e-6ee4-4f89-84cc-133a9545f4f7

**Comment by aimas-lund** [comment]
Hi @MandingoMagnus and @victorlico. First of all, I'm happy to see your interest in my little university project. I kinda just botched this together to demonstrate some possibilities using this gimbal camera for live optical tracking, so I never really needed it to be super robust.
Regrettably, this repo is not one that I, or anyone else, are actively maintaining.

Your best cause of action might be to look at the work of some of the guys who forked this repo. Also feel free to fork this project and make your own modifications.

I wish you good fortune with your projects 🚀
